// Generated by CoffeeScript 1.3.3
(function() {
  var $, addCloneAction, addField, baseurl, ticketid, _0, _ref;

  $ = jQuery;

  _ref = /(.*)\/ticket\/(\d+)/.exec(location.href), _0 = _ref[0], baseurl = _ref[1], ticketid = _ref[2];

  addField = function(form, name, value) {
    return form.append($("<input type=\"hidden\" name=\"field_" + name + "\" value=\"" + value + "\">"));
  };

  addCloneAction = function(container) {
    var form, name, oldvalue;
    form = $("<form action=\"" + baseurl + "/newticket\" method=\"post\">\n <div class=\"inlinebuttons\">\n  <input type=\"submit\" name=\"clone\"\n         value=\"" + (_("Clone")) + "\"\n         title=\"" + (_("Create a new ticket from this comment")) + "\">\n  <input type=\"hidden\" name=\"__FORM_TOKEN\" value=\"" + form_token + "\">\n  <input type=\"hidden\" name=\"preview\" value=\"\">\n </div>\n</form>");
    for (name in old_values) {
      oldvalue = old_values[name];
      if (name !== "id" && name !== "summary" && name !== "description" && name !== "status" && name !== "resolution") {
        addField(form, name, oldvalue);
      }
    }
    return container.each(function() {
      var cform, cnum_a_href, comment;
      comment = $('.comment p', $(this).parent()).text();
      if (!comment) {
        return;
      }
      cnum_a_href = $('h3 .cnum a', $(this).parent()).attr('href');
      cform = form.clone();
      addField(cform, 'summary', _("(part of #%(ticketid)s) %(summary)s", {
        ticketid: ticketid,
        summary: old_values['summary']
      }));
      addField(cform, 'description', _("Copied from [%(source)s]:\n----\n%(description)s", {
        source: "ticket:" + ticketid + cnum_a_href,
        description: comment
      }));
      return $(this).prepend(cform);
    });
  };

  $(document).ready(function() {
    if (typeof old_values !== "undefined" && old_values !== null) {
      return addCloneAction($('#changelog .change').has('.cnum').find('.trac-ticket-buttons'));
    }
  });

}).call(this);
